### ISSUE TITLE
全局背景虚化图不生效

### ISSUE THREAD

**Issue by Leonkeen** [850552586/gridea-theme-fog#12]
你好，设置了一下全局背景虚化，首页的位置不生效，还是一片白，很丑，求助（对于小白真的太难了 ┭┮﹏┭┮），方便的话可以帮忙看一下吗，指路：
https://leonkeen.github.io/
非常感谢！

**Comment by 850552586** [comment]
欢迎进群交流咨询该问题。

**Comment by 850552586** [comment]
欢迎进群交流该问题
QQ群号 1139494873
群二维码地址在这篇介绍中有https://ericam.top/post/gridea-zhu-ti-fog-geng-xin-ri-zhi/

如果文章中出现了背景图，那么主页也会有（单独不出现可能是网速加载问题
