### ISSUE TITLE
关于颜色

### ISSUE THREAD

**Issue by xi2oh2co3** [850552586/gridea-theme-fog#14]
我的博客调了一下颜色，结果topic那个显示就全部变白了，效果很不好，我看了一下也没有设置这个颜色的，求问这是为什么~
[案发现场](xi2oh2co3.github.io)
直接看第一篇博客就是！

**Comment by 850552586** [comment]
你说的是文章索引嘛？在你的文章里会显示两个索引，这个索引是自动生成的，所以你可以把自己post里自己编写的索引删除。
