### ISSUE TITLE
fog主题和Gridea结合之后，同步失败

### ISSUE THREAD

**Issue by shangguan-chenxi** [850552586/gridea-theme-fog#15]
在主题的默认配置的情况下，应用了主题之后，点击同步会显示失败，不知道是不是Gridea的版本和主题不匹配的原因

**Comment by aqrx-os** [comment]
不会的，是你自身的原因，你是否更改过json文件及Git文件夹

**Comment by shangguan-chenxi** [comment]
并没有改过json或者Git目录，是解压出来就直接用的
