### ISSUE TITLE
控制台报错【Uncaught ReferenceError: aplayerbtnInit is not defined】

### ISSUE THREAD

**Issue by superkoenigsegg** [850552586/gridea-theme-fog#16]
版本号
Gridea: 0.9.2
fog: 0.7-0.9
试了0.7，0.8，0.9三个版本均有问题
问题描述
使用fog主题，无法预览；网页白屏，控制台错误信息【Uncaught ReferenceError: aplayerbtnInit is not defined】

**Comment by 850552586** [comment]
进群咨询。

**Comment by Cactus521** [comment]
我也出现了同样的错误
