### ISSUE TITLE
是否考虑增加社交模块全局开关

### ISSUE THREAD

**Issue by GWan1234** [850552586/gridea-theme-fog#27]
RT 主题里面有个板块是社交，可以添加github，b站等链接，这部分不需要的话能否增加一个全局开关，关闭所有的社交接口（包括web端的图标）

**Comment by 850552586** [comment]
可以

**Comment by GWan1234** [comment]
> 可以

该如何修改呢？或者说下一版可以考虑加入这个功能。

**Comment by 850552586** [comment]
> > 可以
> 
> 该如何修改呢？或者说下一版可以考虑加入这个功能。

下个版本，很快更新
