### ISSUE TITLE
文章图片来源

### ISSUE THREAD

**Issue by supercatreal** [850552586/gridea-theme-fog#5]
文章封面的图片上自定义的还是随机的呢?两种方法都可以吗?自定义的话感觉好麻烦。😂

**Comment by 850552586** [comment]
文章封面是写文章里的呀。

**Comment by 850552586** [comment]
文章封面是写文章里加的呀。

**Comment by 850552586** [comment]
主题自定义里都是设置背景图片之类的。

**Comment by supercatreal** [comment]
> 主题自定义里都是设置背景图片之类的。

知道啦，还是希望gridea支持自动随机添加图片呢

**Comment by diego3893** [comment]
大佬问一下，主题设置的背景图片可以使用API而非外链的唯一图片吗？
