### ISSUE TITLE
对于Markdown代码语法的支持不精确

### ISSUE THREAD

**Issue by 1dayluo** [850552586/gridea-theme-fog#6]
目前匹配到的MD语法：
- 四个` 包围起来的代码段
- 单个`包围起来的代码段

只想匹配到的:
四个` 包围起来的代码段

一张图说事：

![微信截图_20200630123012](https://user-images.githubusercontent.com/31794217/86083849-ed44ea00-bacd-11ea-81ee-7119f1a66482.png)
我这不显示图片了。。。。贴图床⬇
https://s1.ax1x.com/2020/06/30/N5A0Mj.png

**Comment by 850552586** [comment]
喔喔，get到问题啦~蟹蟹反馈
